package cn.cntv.app.ipanda.db.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "collect".
 */
public class FavoriteEntity {

    private String object_id;
    private String user_id;
    private String collect_id;
    private String object_title;
    private String object_title2;
    private String object_logo;
    private String object_url;
    private String video_pid;
    private Long collect_date;
    private Integer collect_type;
    private Integer pageSource;
    private String product;
    private Integer flag;
    private String videoLength;
    private String isUploadSucc;
    private Boolean isShowEditUi;
    private Boolean isChecked;
    private Boolean isSingleVideo;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public FavoriteEntity() {
    }

    public FavoriteEntity(String object_id) {
        this.object_id = object_id;
    }

    public FavoriteEntity(String object_id, String user_id, String collect_id, String object_title, String object_title2, String object_logo, String object_url, String video_pid, Long collect_date, Integer collect_type, Integer pageSource, String product, Integer flag, String videoLength, String isUploadSucc, Boolean isShowEditUi, Boolean isChecked, Boolean isSingleVideo) {
        this.object_id = object_id;
        this.user_id = user_id;
        this.collect_id = collect_id;
        this.object_title = object_title;
        this.object_title2 = object_title2;
        this.object_logo = object_logo;
        this.object_url = object_url;
        this.video_pid = video_pid;
        this.collect_date = collect_date;
        this.collect_type = collect_type;
        this.pageSource = pageSource;
        this.product = product;
        this.flag = flag;
        this.videoLength = videoLength;
        this.isUploadSucc = isUploadSucc;
        this.isShowEditUi = isShowEditUi;
        this.isChecked = isChecked;
        this.isSingleVideo = isSingleVideo;
    }

    public String getObject_id() {
        return object_id;
    }

    public void setObject_id(String object_id) {
        this.object_id = object_id;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public String getCollect_id() {
        return collect_id;
    }

    public void setCollect_id(String collect_id) {
        this.collect_id = collect_id;
    }

    public String getObject_title() {
        return object_title;
    }

    public void setObject_title(String object_title) {
        this.object_title = object_title;
    }

    public String getObject_title2() {
        return object_title2;
    }

    public void setObject_title2(String object_title2) {
        this.object_title2 = object_title2;
    }

    public String getObject_logo() {
        return object_logo;
    }

    public void setObject_logo(String object_logo) {
        this.object_logo = object_logo;
    }

    public String getObject_url() {
        return object_url;
    }

    public void setObject_url(String object_url) {
        this.object_url = object_url;
    }

    public String getVideo_pid() {
        return video_pid;
    }

    public void setVideo_pid(String video_pid) {
        this.video_pid = video_pid;
    }

    public Long getCollect_date() {
        return collect_date;
    }

    public void setCollect_date(Long collect_date) {
        this.collect_date = collect_date;
    }

    public Integer getCollect_type() {
        return collect_type;
    }

    public void setCollect_type(Integer collect_type) {
        this.collect_type = collect_type;
    }

    public Integer getPageSource() {
        return pageSource;
    }

    public void setPageSource(Integer pageSource) {
        this.pageSource = pageSource;
    }

    public String getProduct() {
        return product;
    }

    public void setProduct(String product) {
        this.product = product;
    }

    public Integer getFlag() {
        return flag;
    }

    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    public String getVideoLength() {
        return videoLength;
    }

    public void setVideoLength(String videoLength) {
        this.videoLength = videoLength;
    }

    public String getIsUploadSucc() {
        return isUploadSucc;
    }

    public void setIsUploadSucc(String isUploadSucc) {
        this.isUploadSucc = isUploadSucc;
    }

    public Boolean getIsShowEditUi() {
        return isShowEditUi;
    }

    public void setIsShowEditUi(Boolean isShowEditUi) {
        this.isShowEditUi = isShowEditUi;
    }

    public Boolean getIsChecked() {
        return isChecked;
    }

    public void setIsChecked(Boolean isChecked) {
        this.isChecked = isChecked;
    }

    public Boolean getIsSingleVideo() {
        return isSingleVideo;
    }

    public void setIsSingleVideo(Boolean isSingleVideo) {
        this.isSingleVideo = isSingleVideo;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
