package cn.cntv.app.ipanda.db.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "livechina_chinnel".
 */
public class LiveChinaChannelEntity {

    private String title;
    private String url;
    private String type;
    private String order;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public LiveChinaChannelEntity() {
    }

    public LiveChinaChannelEntity(String title) {
        this.title = title;
    }

    public LiveChinaChannelEntity(String title, String url, String type, String order) {
        this.title = title;
        this.url = url;
        this.type = type;
        this.order = order;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getOrder() {
        return order;
    }

    public void setOrder(String order) {
        this.order = order;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
