package cn.cntv.app.ipanda.db.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "playhistory".
 */
public class PlayHistoryEntity {

    private Integer sign;
    private String videoType;
    private String title;
    private String timeLenth;
    private String vid;
    private String videoImg;
    private String uid;
    private String pid;
    private String pageurl;
    private String ip;
    private Long playtime;
    private String client;
    private String clienttype;
    private String position;
    private Boolean ischeck;
    private Boolean isSingleVideo;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public PlayHistoryEntity() {
    }

    public PlayHistoryEntity(String pid) {
        this.pid = pid;
    }

    public PlayHistoryEntity(Integer sign, String videoType, String title, String timeLenth, String vid, String videoImg, String uid, String pid, String pageurl, String ip, Long playtime, String client, String clienttype, String position, Boolean ischeck, Boolean isSingleVideo) {
        this.sign = sign;
        this.videoType = videoType;
        this.title = title;
        this.timeLenth = timeLenth;
        this.vid = vid;
        this.videoImg = videoImg;
        this.uid = uid;
        this.pid = pid;
        this.pageurl = pageurl;
        this.ip = ip;
        this.playtime = playtime;
        this.client = client;
        this.clienttype = clienttype;
        this.position = position;
        this.ischeck = ischeck;
        this.isSingleVideo = isSingleVideo;
    }

    public Integer getSign() {
        return sign;
    }

    public void setSign(Integer sign) {
        this.sign = sign;
    }

    public String getVideoType() {
        return videoType;
    }

    public void setVideoType(String videoType) {
        this.videoType = videoType;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getTimeLenth() {
        return timeLenth;
    }

    public void setTimeLenth(String timeLenth) {
        this.timeLenth = timeLenth;
    }

    public String getVid() {
        return vid;
    }

    public void setVid(String vid) {
        this.vid = vid;
    }

    public String getVideoImg() {
        return videoImg;
    }

    public void setVideoImg(String videoImg) {
        this.videoImg = videoImg;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public String getPid() {
        return pid;
    }

    public void setPid(String pid) {
        this.pid = pid;
    }

    public String getPageurl() {
        return pageurl;
    }

    public void setPageurl(String pageurl) {
        this.pageurl = pageurl;
    }

    public String getIp() {
        return ip;
    }

    public void setIp(String ip) {
        this.ip = ip;
    }

    public Long getPlaytime() {
        return playtime;
    }

    public void setPlaytime(Long playtime) {
        this.playtime = playtime;
    }

    public String getClient() {
        return client;
    }

    public void setClient(String client) {
        this.client = client;
    }

    public String getClienttype() {
        return clienttype;
    }

    public void setClienttype(String clienttype) {
        this.clienttype = clienttype;
    }

    public String getPosition() {
        return position;
    }

    public void setPosition(String position) {
        this.position = position;
    }

    public Boolean getIscheck() {
        return ischeck;
    }

    public void setIscheck(Boolean ischeck) {
        this.ischeck = ischeck;
    }

    public Boolean getIsSingleVideo() {
        return isSingleVideo;
    }

    public void setIsSingleVideo(Boolean isSingleVideo) {
        this.isSingleVideo = isSingleVideo;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
